name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

env:    # configure environment variables for git commits
  actor: "41898282+github-actions[bot]"
  token: ${{ secrets.GITHUB_TOKEN }}
  repo: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::styler, any::lintr  # also install styler & lintr
          needs: check
          working-directory: bionitio
      - name: Configure git  # these use the environment variables we set above
        run: |
          git config --local user.email "${actor}@users.noreply.github.com"
          git config --local user.name "$actor"
      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--as-cran")'
          working-directory: bionitio
      - name: Style & lint
        run: |
            styler::use_tidy_style("bionitio")  # change your package path here
            lintr::lint_package("bionitio")     # and here
        shell: Rscript {0}
      - name: Commit and push changes
        run: |
          git add bionitio/R/\*  # change the path to your R source files here
          git commit -m "🎨 Style code" || echo "No changes to commit"
          git push
